In [1]:
from __future__ import print_function
import torch

In [2]:
# 未初始化矩阵
x = torch.empty(5, 3)
print(x)

tensor([[1.6069e-23, 4.5768e-41, 1.6069e-23],
        [4.5768e-41,        nan, 0.0000e+00],
        [7.6194e+31, 1.5564e+28, 1.8484e+31],
        [1.8370e+25, 1.4603e-19, 2.7517e+12],
        [7.5338e+28, 3.0313e+32, 6.3828e+28]])


In [3]:
# 随机初始化矩阵
x = torch.rand(5, 3)
print(x)

tensor([[0.9183, 0.1517, 0.0573],
        [0.1255, 0.7102, 0.2161],
        [0.6399, 0.1737, 0.1949],
        [0.7991, 0.6763, 0.1508],
        [0.1144, 0.4291, 0.9165]])


In [4]:
# 矩阵填充0，dtype
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [5]:
# 创建tensor
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [6]:
# 由已知tensor创建一个新的
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)
# dtype覆盖
x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-1.7982, -1.0145, -0.7404],
        [-0.8385, -1.8094, -0.2190],
        [ 0.2683, -0.8765, -0.0441],
        [-0.1450, -1.7622, -0.8526],
        [ 0.0728, -0.3255, -0.0478]])


In [7]:
print(x.size())

torch.Size([5, 3])


In [8]:
y = torch.rand(5, 3)
# 直接+
print(x + y)

tensor([[-1.0112, -0.9298, -0.7298],
        [-0.8345, -1.7715,  0.4426],
        [ 1.1600,  0.0364,  0.7761],
        [ 0.7378, -1.5478,  0.0489],
        [ 0.5285,  0.1279,  0.0175]])


In [9]:
# torch +
print(torch.add(x, y))

tensor([[-1.0112, -0.9298, -0.7298],
        [-0.8345, -1.7715,  0.4426],
        [ 1.1600,  0.0364,  0.7761],
        [ 0.7378, -1.5478,  0.0489],
        [ 0.5285,  0.1279,  0.0175]])


In [10]:
# torch output
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[-1.0112, -0.9298, -0.7298],
        [-0.8345, -1.7715,  0.4426],
        [ 1.1600,  0.0364,  0.7761],
        [ 0.7378, -1.5478,  0.0489],
        [ 0.5285,  0.1279,  0.0175]])


In [11]:
# 给y加x
y.add_(x)
print(y)

tensor([[-1.0112, -0.9298, -0.7298],
        [-0.8345, -1.7715,  0.4426],
        [ 1.1600,  0.0364,  0.7761],
        [ 0.7378, -1.5478,  0.0489],
        [ 0.5285,  0.1279,  0.0175]])


In [14]:
print(x)
# 取第2列
print(x[:, 1])

tensor([[ 0.4410,  2.2341, -0.4061,  0.1603],
        [-1.2709,  0.8508, -0.4176,  0.4953],
        [ 0.4538,  1.6978, -0.4609,  0.0496],
        [ 1.5301, -1.3016, -0.5579, -1.6164]])
tensor([ 2.2341,  0.8508,  1.6978, -1.3016])


In [13]:
x = torch.randn(4, 4)
# resize tensor
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [15]:
x = torch.randn(1)
print(x)
# 一个元素的tensor，获取number
print(x.item())

tensor([1.4605])
1.4604688882827759


In [17]:
a = torch.ones(5)
print(a)
# tensor 转 numpy
b = a.numpy()
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [18]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [19]:
import numpy as np
a = np.ones(5)
# numpy 转 tensor
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [20]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

tensor([2.4605], device='cuda:0')
tensor([2.4605], dtype=torch.float64)
